# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


clusterName: "9c-dev-v2"
logLevel: "debug"

global:
  validatorPath: "validator-ex.dpos-external-testing.svc.cluster.local"
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-596c24498906fd03490d7fad614965450594c566-arm64v8"

  appProtocolVersion: "1/fe4829C1650d3d5FC552516576731DBE74A5f3B1/MEQCID.oqBAHrJRhQ0myPP6eAMjnoPKz0mMn+btIdHdQ94QxAiAdV2L0l8GfQ0nat7g.6xClCWW9ue2rmarV5hBESUcwbQ=="
  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"
  trustedAppProtocolVersionSigner: "02dac8e104ec5dec045dddb9939d83722cc0e1df523795bface7ed10ae56187638"
  headlessAppsettingsPath: "https://9c-cluster-config.s3.us-east-2.amazonaws.com/9c-dev/appsettings.json"

  peerStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31234"

  resetSnapshot: true
  rollbackSnapshot: true

externalSecret:
  enabled: true
  prefix: 9c-dev-v2
  pkPrefixOverride: 9c-internal-v2

validator:
  count: 1

  loggingEnabled: true

  consensusSeedStrings:
  - "033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31235"

  hosts:
  - "validator-ex.dpos-external-testing.svc.cluster.local"

  extraArgs:
  - --tx-quota-per-signer=1
  - --consensus-target-block-interval=6500

  nodeSelector:
    eks.amazonaws.com/nodegroup: general-m7g_2xl_2c
